WebUI/Controllers/AdminOrderController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class AdminOrderController : Controller
    {
        //private EFOrderRepository repository = new EFOrderRepository();

        private IOrderRepository repository;

        public AdminOrderController(IOrderRepository repo)
        {
            repository = repo;
        }

        [Authorize(Users = "Admin")]
        public ViewResult List(int query = 0)
        {
            OrderListViewModel model = new OrderListViewModel
            {
                Orders = repository.GetAllOrders().Where(b => query == 0 || b.OrderId == query)
            };

            return View(model);
        }

        //[Authorize]
        //public ViewResult Edit(int orderId)
        //{
        //    Order order = repository.GetAllOrders().FirstOrDefault(b => b.OrderId == orderId);

        //    return View(order);
        //}

        //[HttpPost]
        //[Authorize]
        //public ActionResult Edit(Order order)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        repository.SaveOrder(order);
        //        TempData["message"] = string.Order("Зміна формату \"{0}\" збережена", order.Name);
        //        return RedirectToAction("List");
        //    }
        //    else
        //    {
        //        return View(order);
        //    }
        //}

        //[Authorize]
        //public ViewResult Add()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[Authorize]
        //public ActionResult Add(Order order)
        //{
        //    TempData["message"] = string.Order(order.OrderId.ToString());

        //    if (ModelState.IsValid)
        //    {
        //        repository.SaveOrder(order);
        //        TempData["message"] = string.Order("Формат \"{0}\" додано", order.Name);
        //        return RedirectToAction("List");
        //    }
        //    else
        //    {
        //        return View();
        //    }
        //}

        public RedirectToRouteResult Remove(int orderId)
        {
            Order order = repository.GetAllOrders().FirstOrDefault(b => b.OrderId == orderId);

            repository.RemoveOrder(order);
            TempData["message"] = "Видалення формату успішне";

            return RedirectToAction("List");
        }
    }
}

WebUI/Controllers/AdminTourController.cs
using Domain.Abstract;
using Domain.Concrete;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class AdminTourController : Controller
    {
        private ITourRepository repository;
        public IFormatRepository formatRepository = new EFFormatRepository();

        public AdminTourController(ITourRepository repo)
        {
            repository = repo;
        }

        public ViewResult Edit(int tourId)
        {
            Tour tour = repository.GetAllTours().FirstOrDefault(b => b.TourId == tourId);

            TourEditViewModel model = new TourEditViewModel
            {
                Tour = tour,
                Formats = formatRepository.GetAllFormats(),
                CurentFormat = tour.FormatId
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Tour tour, int formatId)
        {
            if (ModelState.IsValid)
            {
                tour.FormatId = formatId;
                repository.SaveTour(tour);
                TempData["message"] = string.Format("Зміна контенту \"{0}\" збережена", tour.Name);
                return RedirectToAction("List");
            }
            else
            {
                TourEditViewModel model = new TourEditViewModel
                {
                    Tour = tour,
                    Formats = formatRepository.GetAllFormats(),
                    CurentFormat = tour.FormatId
                };
                return View(model);
            }
        }

        public ViewResult Add()
        {
            TourAddViewModel model = new TourAddViewModel
            {
                Tour = new Tour(),
                Formats = formatRepository.GetAllFormats(),
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(Tour tour, int formatId)
        {
            if (ModelState.IsValid)
            {
                tour.FormatId = formatId;
                repository.SaveTour(tour);
                TempData["message"] = string.Format("Формат \"{0}\" додано", tour.Name);
                return RedirectToAction("List");
            }
            else
            {
                return View();
            }
        }

        [Authorize(Users = "Admin")]
        public ViewResult List(int format = 0, string query = null, string type = null)
        {
            TourListViewModel model = new TourListViewModel
            {
                Tours = repository.GetAllTours()
                    .Where(b => format == 0 || b.Format.FormatId == format)
                    .Where(b => type == null || b.Type == type)
                    .Where(b => query == null || b.Name == query || b.Description == query),
                Types = repository.GetAllTours()
                    .Select(tour => tour.Type)
                    .Distinct()
                    .OrderBy(x => x),
                Formats = formatRepository.GetAllFormats(),
                CurentFormat = format,
                CurentType = type
            };

            return View(model);
        }

        //[Authorize]
        public RedirectToRouteResult Remove(int tourId)
        {
            Tour tour = repository.GetAllTours().FirstOrDefault(b => b.TourId == tourId);

            repository.RemoveTour(tour);
            TempData["message"] = string.Format("Видалення контенту успішне");

            return RedirectToAction("List");
        }
    }
}

WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Concrete;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private ITourRepository repository;
        public CartController(ITourRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public ViewResult Order(Cart cart, decimal sum)
        {
            IOrderRepository orderRepository = new EFOrderRepository();

            Order order = new Order
            {
                Sum = sum,
                UserId = Convert.ToInt32(User.Identity.Name)
            };
            orderRepository.SaveOrder(order);

            cart.Clear();

            return View(order.OrderId);
        }

        [Authorize]
        public RedirectToRouteResult AddToCart(Cart cart, int tourId, string returnUrl)
        {
            Tour tour = repository.GetAllTours()
                .FirstOrDefault(b => b.TourId == tourId);

            if (tour != null)
            {
                cart.AddItem(tour, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int tourId, string returnUrl)
        {
            Tour tour = repository.GetAllTours()
                .FirstOrDefault(b => b.TourId == tourId);

            if (tour != null)
            {
                cart.RemoveLine(tour);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private ITourRepository repository;

        public NavController(ITourRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string type = null)
        {
            ViewBag.SelectedType = type;

            IEnumerable<string> types = repository.GetAllTours()
                .Select(tour => tour.Type)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(types);
        }
    }
}

WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <title>@ViewBag.Title</title>
    <style>
                html {
                    position: relative;
                    min-height: 100%;
                }

                body {
                    /* Margin bottom by footer height */
                    margin-bottom: 60px;
                }

                .footer {
                    position: absolute;
                    bottom: 0;
                    width: 100%;
                    /* Set the fixed height of the footer here */
                    height: 60px;
                    line-height: 60px; /* Vertically center the text there */
                    background-color: #f5f5f5;
                }


                /* Custom page CSS
        -------------------------------------------------- */
                /* Not required for template or sticky footer method. */

                body > .container {
                    padding: 60px px 0;
                }

                .footer > .container {
                    padding-right: 15px;
                    padding-left: 15px;
                }

                code {
                    font-size: 80%;
                }
    </style>
</head>
<body>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/Admin/Index">Адмін панель</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <div class="nav-link">@Html.ActionLink("Тури", "List", "AdminTour")</div>
                </li>
                <li class="nav-item">
                    <div class="nav-link">@Html.ActionLink("Міста", "List", "AdminFormat")</div>
                </li>
                <li class="nav-item">
                    <div class="nav-link">@Html.ActionLink("Замовлення", "List", "AdminOrder")</div>
                </li>
            </ul>
            @*<div class="form-inline mt-2 mt-md-0">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.RouteLink("Вийти",
                            new
                            {
                                controller = "User",
                                action = "SignOut"
                            }, new
                            {
                                @class = "btn btn-outline-success my-2 my-sm-0"
                            })
                    }
                    else
                    {
                        @Html.RouteLink("Ввійти",
                            new
                            {
                                controller = "User",
                                action = "Login"
                            }, new
                            {
                                @class = "btn btn-outline-success my-2 my-sm-0"
                            })
                    }

                </div>*@
        </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
        <br>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }

        @if (TempData["err-message"] != null)
        {
            <div class="alert alert-danger">@TempData["err-message"]</div>
        }
        <br>
        <div class="row">
            @RenderBody()
        </div>


    </main>
    <br>
    <footer class="footer">
        <div class="container">
            <span class="text-muted">Варіант №2.</span>
        </div>
    </footer>

</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />

    <link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        html {
            position: relative;
            min-height: 100%;
        }

        body {
            /* Margin bottom by footer height */
            margin-bottom: 60px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            /* Set the fixed height of the footer here */
            height: 60px;
            line-height: 60px; /* Vertically center the text there */
            background-color: #f5f5f5;
        }


        /* Custom page CSS
-------------------------------------------------- */
        /* Not required for template or sticky footer method. */

        body > .container {
            padding: 60px 15px 0;
        }

        .footer > .container {
            padding-right: 15px;
            padding-left: 15px;
        }

        code {
            font-size: 80%;
        }
    </style>
</head>
<body>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/">TravelAgency</a>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto"></ul>
                <div class="form-inline mt-2 mt-md-0">
                    @Html.Action("Summary", "Cart")
                    _
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.RouteLink("Вийти",
                            new
                            {
                                controller = "User",
                                action = "SignOut"
                            }, new
                            {
                                @class = "btn btn-sm btn-outline-success"
                            })
                    }
                    else
                    {
                        @Html.RouteLink("Ввійти",
                            new
                            {
                                controller = "User",
                                action = "Login"
                            }, new
                            {
                                @class = "btn btn-sm btn-outline-success"
                            })
                    }
                </div>

            </div>
        </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
        <br>
        <div class="row">
            <div class="col-md-8">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">@TempData["message"]</div>
                }

                @if (TempData["err-message"] != null)
                {
                    <div class="alert alert-danger">@TempData["err-message"]</div>
                }
                @RenderBody()
            </div>
            <div class="col-md-4">
                @Html.Action("Menu", "Nav")

            </div>
        </div>


    </main>

    <br>
    <footer class="footer">
        <div class="container">
            <span class="text-muted">Place sticky footer content here.</span>
        </div>
    </footer>

</body>
</html>